blank_issues_enabled: false
contact_links:
  - name: Question (via Telegram groups)
    url: https://github.com/coinsambacom/js-exchanges-connector#resources
    about: Ask and answer questions about coinsamba@js-exchanges-connector
  - name: Question (via GitHub Discussions)
    url: https://github.com/coinsambacom/js-exchanges-connector/discussions/categories/q-a
    about: Ask and answer questions about coinsamba@js-exchanges-connector