name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Use Node.js 20.5.0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.0

      # Install packages
      - name: Install packages
        run: yarn

      # Publish to npm
      - name: Publish to npm
        run: |
          npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
          npm publish --ignore-scripts
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
